CREATE TABLE order_book
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    exchange VARCHAR(255),
    pair     VARCHAR(255),
    CONSTRAINT unique_order UNIQUE (exchange, pair)
);

CREATE TABLE asks
(
    id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_book_id INT REFERENCES order_book (id),
    price         FLOAT8,
    base_qty      FLOAT8
);

CREATE TABLE bids
(
    id            int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_book_id INT REFERENCES order_book (id),
    price         FLOAT8,
    base_qty      FLOAT8
);
CREATE TABLE order_history
(
    id                    int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_name           VARCHAR(255) NOT NULL,
    exchange_name         VARCHAR(255) NOT NULL,
    label                 VARCHAR(255) NOT NULL,
    pair                  VARCHAR(255) NOT NULL,
    side                  VARCHAR(50)  NOT NULL,
    type                  VARCHAR(50)  NOT NULL,
    base_qty              FLOAT8       NOT NULL,
    price                 FLOAT8       NOT NULL,
    algorithm_name_placed VARCHAR(255) NOT NULL,
    lowest_sell_prc       FLOAT8       NOT NULL,
    highest_buy_prc       FLOAT8       NOT NULL,
    commission_quote_qty  FLOAT8       NOT NULL,
    time_placed           TIMESTAMP    NOT NULL
);
